release:
  development_branch: master
  release_branch: prod
changelog:
  path: ./CHANGLOG.md
  item_template: |-
    {{range .Sections}}### {{.StartTaggedCommit.Tag}} - {{.EndTaggedCommit.Tag}} ({{.EndTaggedCommit.Date.Format "2006 Jan 02"}})

    {{range $idx, $commit := .Commits}}* [{{trimm $commit.Hash 7}}] {{$commit.Author}} - {{$commit.Message}} ({{$commit.Date.Format "2006 Jan 02"}})
    {{end}}
    {{end}}
